FROM openjdk:11-jre
ADD ./source-core-0.2.6.zip /source-core-0.2.6.zip

ADD ./apache-skywalking-apm-bin /apache-skywalking-apm-bin
ADD ./agent.config /apache-skywalking-apm-bin/agent/config/agent.config
ADD ./customize_enhance.xml /apache-skywalking-apm-bin/agent/config/customize_enhance.xml

ENV SOURCE_CONFIG=docker.json
ENV JAVA_OPTS=-javaagent:/apache-skywalking-apm-bin/agent/skywalking-agent.jar

RUN unzip *.zip
CMD ["./source-core-0.2.6/bin/source-core"]