FROM sourceplusplus/spp-platform:0.2.1

ADD ./config/spp-platform.crt /opt/sourceplusplus/config
ADD ./config/spp-platform.key /opt/sourceplusplus/config
ADD ./config/spp-platform.yml /opt/sourceplusplus/config