FROM sourceplusplus/spp-platform:latest

ADD ./config/spp-platform.crt /opt/sourceplusplus/config
ADD ./config/spp-platform.key /opt/sourceplusplus/config
ADD ./config/spp-platform.yml /opt/sourceplusplus/config