FROM openjdk:11-jre
ADD ./spp-example-webapp-boot-1.0-SNAPSHOT.zip /spp-example-webapp-boot-1.0-SNAPSHOT.zip

COPY ./apache-skywalking-apm-8.8.1.tar.gz /apache-skywalking-apm-8.8.1.tar.gz
RUN tar -xzf ./apache-skywalking-apm-8.8.1.tar.gz
#RUN mv /apache-skywalking-apm-bin/agent/activations/apm-toolkit-trace-activation-8.7.0.jar /apache-skywalking-apm-bin/agent/plugins/

ADD ./agent.config /apache-skywalking-apm-bin/agent/config/agent.config
#ADD ./customize_enhance.xml /apache-skywalking-apm-bin/agent/config/customize_enhance.xml

ENV JAVA_OPTS="-javaagent:/apache-skywalking-apm-bin/agent/skywalking-agent.jar"
ENV SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap:11800

RUN unzip *.zip
CMD ["./spp-example-webapp-boot-1.0-SNAPSHOT/bin/spp-example-webapp"]